angular7アップデート
ERROR in src/app/core/service/user.service.ts(21,39): error TS2339: Property 'uid' does not exist on type 'UserCredential'.
src/app/auth.guard.ts(17,34): error TS2339: Property 'map' does not exist on type 'Observable<User>'.
エラーが出てしまいます